version: "3"
services:
  postgres:
    image: postgres:10.4-alpine
    environment:
      POSTGRES_DB: local
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  application:
    image: kotlin-spring-webflux
    build:
      context: .
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: local
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - "8080:8080"

volumes:
  postgres_data: {}
